version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DATABASE: ${DATABASE_SCHEMA}
      POSTGRES_DATABASES: ${DATABASE_NAME},test
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - learningci-postgres:/var/lib/postgres/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  learningci-postgres:


